#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path

PRD_STATUSES = {"Draft", "Approved", "In Progress", "Completed", "Cancelled"}
TASK_STATUSES = {"Todo", "In Progress", "Blocked", "Done", "Cancelled"}
PHASES = {"interview", "spec", "overview", "tasks", "implement", "done"}
MARKER = "<!-- generated by spec-driven-dev/scripts/prd_index.py; do not edit by hand -->"


def parse_value(raw):
    value = raw.split(" #", 1)[0].strip()
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        return [item.strip().strip("\"'") for item in inner.split(",") if item.strip()]
    return value.strip("\"'")


def frontmatter(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    data, current = {}, None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line.startswith(("  - ", "- ")) and current:
            data.setdefault(current, [])
            if isinstance(data[current], list):
                data[current].append(parse_value(line.split("- ", 1)[1]))
            continue
        if ":" in line and not line.startswith(" "):
            key, raw = line.split(":", 1)
            current = key.strip()
            data[current] = parse_value(raw) if raw.strip() else []
    return data


def load_prd(prd_dir):
    spec = frontmatter(prd_dir / "spec.md")
    tasks = []
    for task_file in sorted(prd_dir.glob("TASK-*.md")):
        task = frontmatter(task_file)
        tasks.append({"id": task.get("id") or task_file.stem[:8], "status": task.get("status", ""), "file": task_file})
    return {"dir": prd_dir, "spec": spec, "tasks": tasks}


def problems(prd):
    found = []
    spec, where = prd["spec"], prd["dir"] / "spec.md"
    if spec.get("status") not in PRD_STATUSES:
        found.append(f"{where}: invalid PRD status {spec.get('status')!r}")
    if spec.get("phase") and spec["phase"] not in PHASES:
        found.append(f"{where}: invalid phase {spec['phase']!r}")
    for task in prd["tasks"]:
        if task["status"] not in TASK_STATUSES:
            found.append(f"{task['file']}: invalid task status {task['status']!r}")
    open_tasks = [task["id"] for task in prd["tasks"] if task["status"] not in ("Done", "Cancelled")]
    if spec.get("status") == "Completed" and open_tasks:
        found.append(f"{where}: Completed but {', '.join(open_tasks)} still open")
    return found


def progress(prd):
    tasks = prd["tasks"]
    if not tasks:
        return "none yet"
    done = sum(1 for task in tasks if task["status"] == "Done")
    active = [task for task in tasks if task["status"] != "Cancelled"]
    cancelled = len(tasks) - len(active)
    suffix = f" ({cancelled} cancelled)" if cancelled else ""
    return f"{done}/{len(active)} done{suffix}: " + ", ".join(task["id"] for task in tasks)


def cell(value):
    return str(value or "-").replace("|", "\\|")


def render(scope, prds):
    rows = [
        f"# PRD Index — {scope}",
        "",
        MARKER,
        "",
        "| ID | Title | Author | Created | Status | Phase | Tasks |",
        "|---|---|---|---|---|---|---|",
    ]
    for prd in prds:
        spec = prd["spec"]
        prd_id = spec.get("id") or prd["dir"].name
        rows.append(
            f"| [{prd_id}](./{prd['dir'].name}/spec.md) | {cell(spec.get('title'))} | {cell(spec.get('author'))} "
            f"| {cell(spec.get('created_at'))} | {cell(spec.get('status'))} | {cell(spec.get('phase'))} | {cell(progress(prd))} |"
        )
    return "\n".join(rows) + "\n"


def collect(root):
    groups = {}
    for spec in sorted(root.rglob("PRD-*/spec.md")):
        groups.setdefault(spec.parent.parent, []).append(load_prd(spec.parent))
    return groups


def scope_name(index_dir, root):
    return index_dir.name if index_dir != root else root.resolve().parent.parent.name


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate and check the PRD indexes of a repo.")
    parser.add_argument("--root", default="docs/prd", help="PRD root directory (default: docs/prd)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail when an index is stale or a status is invalid")
    mode.add_argument("--status", action="store_true", help="print every PRD with its phase and task progress")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.is_dir():
        print(f"no PRD root at {root}", file=sys.stderr)
        return 1

    groups = collect(root)
    issues = [issue for prds in groups.values() for prd in prds for issue in problems(prd)]

    if args.status:
        for index_dir, prds in groups.items():
            print(scope_name(index_dir, root))
            for prd in prds:
                spec = prd["spec"]
                print(f"  {spec.get('id') or prd['dir'].name}  {spec.get('status', '?')}  phase={spec.get('phase', '-')}  {progress(prd)}")
        for issue in issues:
            print(f"! {issue}", file=sys.stderr)
        return 1 if issues else 0

    stale = []
    for index_dir, prds in groups.items():
        index = index_dir / "README.md"
        content = render(scope_name(index_dir, root), prds)
        current = index.read_text(encoding="utf-8") if index.exists() else ""
        if current == content:
            continue
        if args.check:
            stale.append(str(index))
        else:
            index.write_text(content, encoding="utf-8")
            print(f"wrote {index}")

    for path in stale:
        print(f"! stale index: {path} (run prd_index.py)", file=sys.stderr)
    for issue in issues:
        print(f"! {issue}", file=sys.stderr)
    return 1 if stale or issues else 0


if __name__ == "__main__":
    sys.exit(main())
